server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  
spring:
  config:
    activate:
      on-profile: default
  cloud:
    gateway:
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
